#!/usr/bin/env python3
"""Train a detector on the exported dataset. Supports ALL classes in
classes.py (data.yaml is generated by export.ts from the same list).

  train.py --type student --data data/realtime/data.yaml --weights yolo11n.pt \
           --epochs 20 --project data/weights --name student_v3

Device: MPS (Apple) or CUDA if available; on pure CPU trains 1 epoch so the
loop still produces a model + metrics without burning hours.

Last stdout line = JSON metrics for the caller:
  {"weights": ".../best.pt", "metrics": {"map50": .., "ball_map50": .., ...}}
"""
import argparse, json, sys

import torch
from ultralytics import YOLO

from classes import CLASSES


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--type", default="student", choices=["student", "teacher"])
    ap.add_argument("--data", required=True)
    ap.add_argument("--weights", default="yolo11n.pt")
    ap.add_argument("--epochs", type=int, default=20)
    ap.add_argument("--imgsz", type=int, default=960)
    ap.add_argument("--project", default="data/weights")
    ap.add_argument("--name", required=True)
    args = ap.parse_args()

    if torch.backends.mps.is_available():
        device = "mps"
    elif torch.cuda.is_available():
        device = "cuda"
    else:
        device = "cpu"
        print("no GPU — training 1 epoch only", file=sys.stderr)
        args.epochs = 1

    model = YOLO(args.weights)
    results = model.train(data=args.data, epochs=args.epochs, imgsz=args.imgsz,
                          device=device, project=args.project, name=args.name,
                          exist_ok=True, verbose=True, patience=10,
                          batch=8 if device != "cpu" else 2)

    best = str(results.save_dir / "weights" / "best.pt")
    val = model.val(data=args.data, device=device, verbose=False)

    metrics = {"map50": float(val.box.map50), "map5095": float(val.box.map)}
    # per-class mAP50 keyed by our class names ("ball_map50", "rim_map50", ...)
    names = val.names if isinstance(val.names, dict) else dict(enumerate(val.names))
    for idx, ap50 in zip(val.box.ap_class_index, val.box.ap50):
        cls = names.get(int(idx), str(idx))
        if cls in CLASSES:
            metrics[f"{cls}_map50"] = float(ap50)
    for cls in CLASSES:
        metrics.setdefault(f"{cls}_map50", 0.0)  # class absent from val set

    out = {"weights": best, "metrics": metrics, "device": device,
           "epochs": args.epochs}
    with open(str(results.save_dir / "metrics.json"), "w") as fh:
        json.dump(out, fh, indent=2)
    print(json.dumps(out))


if __name__ == "__main__":
    main()
